spring:
  application:
    name: expensetracker
  datasource:
    url: jdbc:mysql://localhost:3306/expensetracker?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always